old/old/Website/urls.py
from django.contrib import admin
from django.urls import path,include
from django_email_verification import urls as email_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('accounts.urls',namespace='account')),
    # path('email/', include(email_urls)),
    path('', include('index.urls')),
    path('blog', include('blog.urls')),
    path('auth/', include('magiclink.urls', namespace='magiclink')),
]

old/old/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name='accounts'
urlpatterns = [
    # path('register', views.register_view, name='register'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('profile', views.profile, name='profile')
]

old/old/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.blog.as_view(), name='blog'),
    path('<slug>', views.entry.as_view(), name='entry'),
]

old/old/templates/index/home.html
{% extends 'index/layout.html' %}
{% load static %}

{% block body %}

<main class='w-auto grid'>
    <section class="gl12 gm12 gs12 gxs12 grid initiative">
        <div class="gl6 gm6 gs12 gxs12 w-auto initiativeImg">
            <img class='w-auto h-auto inImg' src="" alt='our initiative'>
        </div>
        <p class="gl6 gm6 gs12 gxs12 initiativeBody">Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Deserunt,
            sequi ut? Dolor
            obcaecati corrupti distinctio error molestiae consequatur, minus saepe totam, accusamus labore illo atque
            laboriosam. Vero odio perferendis doloribus Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Perspiciatis, fuga dolores. Earum repudiandae quam, cupiditate suscipit aspernatur necessitatibus voluptatem
            beatae ipsa repellendus iste alias, voluptatum ipsam odio, ut quaerat sequi?Lorem ipsum, dolor sit amet
            consectetur adipisicing elit. Inventore debitis nulla necessitatibus quo molestiae ratione nihil suscipit
            fuga voluptas, minima pariatur dolores numquam eligendi libero ad hic vero exercitationem maxime</p>
    </section>


    <section class="gl12 gm12 gs12 gxs12 grid rates">
        <div class="gl12 gm12 gs12 gxs12 w-auto ratesTop">
            <img class="ratesImg" src="{% static 'images/rates.jpg' %}">
            <span>RATES</span>
        </div>
        <div class='gl3 gm3 rates-odd gs6 gxs12 flexV w-auto'>
            <h4 class="w-auto t-auto ratesHeading">Silver</h4>
            <p class='ratesCost w-auto t-auto'>$300/month</p>
            <p class="ratesBody w-auto t-auto">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus ipsum
                perspiciatis
                doloribus exercitationem! In debitis necessitatibus nulla praesentium est ratione amet modi dolorem
                cumque
                facere facilis quo, laboriosam sed libero?</p>
        </div>
        <div class='gl3 gm3 rates-even gs6 gxs12 flexV'>
            <h4 class="w-auto t-auto ratesHeading">Gold</h4>
            <p class='ratesCost w-auto t-auto'>$400/month</p>
            <p class="ratesBody w-auto t-auto">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus ipsum
                perspiciatis
                doloribus exercitationem! In debitis necessitatibus nulla praesentium est ratione amet modi dolorem
                cumque
                facere facilis quo, laboriosam sed libero?</p>
        </div>
        <div class='gl3 gm3 rates-odd gs6 gxs12 flexV'>
            <h4 class="w-auto t-auto ratesHeading">Platinum</h4>
            <p class='ratesCost w-auto t-auto'>$500/month</p>
            <p class="ratesBody w-auto t-auto">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus ipsum
                perspiciatis
                doloribus exercitationem! In debitis necessitatibus nulla praesentium est ratione amet modi dolorem
                cumque
                facere facilis quo, laboriosam sed libero?</p>
        </div>
        <div class='gl3 gm3 rates-even gs6 gxs12 flexV'>
            <h4 class="w-auto t-auto ratesHeading">Diamond</h4>
            <p class='ratesCost w-auto t-auto'>$1000/month</p>
            <p class="ratesBody w-auto t-auto">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus ipsum
                perspiciatis
                doloribus exercitationem! In debitis necessitatibus nulla praesentium est ratione amet modi dolorem
                cumque
                facere facilis quo, laboriosam sed libero?</p>
        </div>
    </section>


    <section class='gl12 gm12 gs12 gxs12 grid team'>
        <h2 class="gl12 gm12 gs12 gxs12 teamHeader">Our Team</h2>

        <div class="gl12 gm12 gs12 gxs12 grid teamBody-top">
            <img class="gl4 gm4 gs6 gxs12 w-auto teamImg" src="">
            <div class='gl3 gm5 gs6 gxs12 teamBody-top-info'><span class="pxs0" data-type="name">Karam Hammoud</span>
                <br /><span data-type="position">-CEO And Director Of Finances</span>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab labore nobis commodi soluta iusto veniam,
                    reprehenderit repellat, dolores repellendus fugiat dolor quisquam dignissimos, esse autem accusamus
                    ut itaque temporibus sed.</p>
            </div>
        </div>

        <div class="gl12 gm12 gs12 gxs12 grid teamBody-bottom">
            <div class='gl5 gm4 ds0 dxs0'></div>
            <div class='gl3 gm4 gs6 gxs12 teamBody-bottom-info'><span data-type="name">Reema O.Adem</span>
                <br /><span data-type="position">-CEO And Director Of Finances</span>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab labore nobis commodi soluta iusto veniam,
                    reprehenderit repellat, dolores repellendus fugiat dolor quisquam dignissimos, esse autem accusamus
                    ut itaque temporibus sed.</p>
            </div>
            <img class="gl4 gm4 gs6 gxs12 w-auto teamImg" src="">
        </div>

    </section>


</main>

<script src="{% static 'js/index.js' %}"></script>

{% endblock %}

old/old/templates/index/jobs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/jobs.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <section class="grid header">
        <h1 class="gl12 gm12 gs12 gxs12 header-h1">JOIN OUR FAMILY</h1>
        <p class="gl12 gm12 gs12 gxs12 header-p">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dicta
            praesentium explicabo velit asperiores magni
            consequatur, cum id, blanditiis numquam repellendus rem, perferendis veritatis! Sequi amet earum possimus
            provident,
            error sunt.</p>
    </section>
    <section class="listing">
        {% for job in data %}
        <div class="b-auto listing-item">
            <span>i</span>
            <p>{{job.title}}</p>
            <div>
                <a href="{{job.get_absolute_url}}">More Info</a>
            </div>
        </div>
        {% endfor %}
    </section>
</body>

</html>

old/old/templates/index/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home{% endblock %}</title>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css' rel='stylesheet'>

</head>

<body>
    <header>
        <nav class='nav'>
            <ul>
                <li class="dl0 dm0 ds0"><span class='fa fa-bars'></span></li>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'jobs' %}">Jobs</a></li>
                <li><a href="{% url 'blog' %}">Blog</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
        <div class='navImage'>
            <img src="{% static 'images/heading.jpg' %}">
        </div>
    </header>
    <main>
        {% block body %}
        {% endblock %}
    </main>

    <footer class='w-auto footer'>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, optio mollitia fuga obcaecati exercitationem iure
        officia sint quisquam voluptate quasi necessitatibus accusamus quos nemo corporis, in earum, reprehenderit
        assumenda sed!Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, optio mollitia fuga obcaecati
        exercitationem iure
        officia sint quisquam voluptate quasi necessitatibus accusamus quos nemo corporis, in earum, reprehenderit
        assumenda sed!Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, optio mollitia fuga obcaecati
        exercitationem iure
        officia sint quisquam voluptate quasi necessitatibus accusamus quos nemo corporis, in earum, reprehenderit
        assumenda sed!Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, optio mollitia fuga obcaecati
        exercitationem iure
        officia sint quisquam voluptate quasi necessitatibus accusamus quos nemo corporis, in earum, reprehenderit
        assumenda sed!Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, optio mollitia fuga obcaecati
        exercitationem iure
        officia sint quisquam voluptate quasi necessitatibus accusamus quos nemo corporis, in earum, reprehenderit
        assumenda sed!Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos, optio mollitia fuga obcaecati
        exercitationem iure
        officia sint quisquam voluptate quasi necessitatibus accusamus quos nemo corporis, in earum, reprehenderit
        assumenda sed!
    </footer>
</body>

</html>

old/old/templates/index/listing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {{ job.title }}
    {{ job.description }}
    {% if not user.is_staff %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input name='file' type="file">
        <input type="submit">
    </form>
    {% endif %}
</body>

</html>